application: miapp-gae
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: static

- url: /(index)?
  upload: index.html
  static_files: index.html

- url: /.*
  script: main.app

